# Generated by Django 5.1.7 on 2025-04-12 13:46

import django.db.models.deletion
import functools
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("feat", "0001_initial"),
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BABProgression",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("attack_bonus_table", models.JSONField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Base attack bonus progressions",
                "ordering": ["attack_bonus_table"],
            },
        ),
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                (
                    "max_level",
                    models.IntegerField(
                        default=20,
                        validators=[
                            functools.partial(
                                utils.validators.validate_integer_in_range,
                                *(),
                                **{"max_value": 20, "min_value": 1},
                            )
                        ],
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "skill_points_per_level",
                    models.IntegerField(
                        default=0,
                        validators=[utils.validators.validate_positive_integer],
                    ),
                ),
                ("spells_per_day", models.JSONField(blank=True, null=True)),
                ("spells_known", models.JSONField(blank=True, null=True)),
                (
                    "bab_progression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="character_class.babprogression",
                        verbose_name="BAB Progression",
                    ),
                ),
                (
                    "hit_die",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.die"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.source",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Character Classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrestigeClassRaceRequirement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="PrestigeClassSkillRankRequirement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "required_ranks",
                    models.IntegerField(
                        default=0,
                        validators=[utils.validators.validate_positive_integer],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BSBProgression",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("save_bonus_table", models.JSONField()),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.ability"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Base save bonus progressions",
                "ordering": ["name", "save_bonus_table"],
            },
        ),
        migrations.CreateModel(
            name="PrestigeCharacterClass",
            fields=[
                (
                    "characterclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="character_class.characterclass",
                    ),
                ),
                (
                    "required_bab",
                    models.IntegerField(
                        default=0,
                        validators=[utils.validators.validate_positive_integer],
                    ),
                ),
                (
                    "other_requirements",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Prestige Classes",
            },
            bases=("character_class.characterclass",),
        ),
        migrations.CreateModel(
            name="ClassAlignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "alignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.alignment",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character_class.characterclass",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="characterclass",
            name="required_alignment",
            field=models.ManyToManyField(
                through="character_class.ClassAlignment", to="common.alignment"
            ),
        ),
        migrations.CreateModel(
            name="ClassBonusLanguage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character_class.characterclass",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.language",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="characterclass",
            name="bonus_languages",
            field=models.ManyToManyField(
                blank=True,
                through="character_class.ClassBonusLanguage",
                to="common.language",
            ),
        ),
        migrations.CreateModel(
            name="ClassBsbProgression",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bsb_progression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="character_class.bsbprogression",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character_class.characterclass",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="characterclass",
            name="bsb_progression",
            field=models.ManyToManyField(
                blank=True,
                through="character_class.ClassBsbProgression",
                to="character_class.bsbprogression",
            ),
        ),
        migrations.CreateModel(
            name="ClassSkill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character_class.characterclass",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="skill.skill"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="characterclass",
            name="class_skills",
            field=models.ManyToManyField(
                blank=True, through="character_class.ClassSkill", to="skill.skill"
            ),
        ),
        migrations.CreateModel(
            name="ClassTrait",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_level_requirement",
                    models.IntegerField(
                        default=1,
                        validators=[utils.validators.validate_positive_integer],
                    ),
                ),
                (
                    "additional_value",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character_class.characterclass",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.trait"
                    ),
                ),
            ],
            options={
                "ordering": ["class_level_requirement"],
            },
        ),
        migrations.AddField(
            model_name="characterclass",
            name="class_traits",
            field=models.ManyToManyField(
                blank=True, through="character_class.ClassTrait", to="common.trait"
            ),
        ),
        migrations.CreateModel(
            name="PrestigeClassFeatRequirement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "feat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="feat.feat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrestigeClassLanguageRequirement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.language",
                    ),
                ),
            ],
        ),
    ]
