# Generated by Django 5.1.7 on 2025-04-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_class", "0001_initial"),
        ("common", "0001_initial"),
        ("feat", "0001_initial"),
        ("race", "0001_initial"),
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestigeclassracerequirement",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="race.race"
            ),
        ),
        migrations.AddField(
            model_name="prestigeclassskillrankrequirement",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="skill.skill"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bsbprogression",
            unique_together={("ability", "save_bonus_table")},
        ),
        migrations.AddField(
            model_name="prestigeclassskillrankrequirement",
            name="prestige_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="character_class.prestigecharacterclass",
            ),
        ),
        migrations.AddField(
            model_name="prestigeclassracerequirement",
            name="prestige_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="character_class.prestigecharacterclass",
            ),
        ),
        migrations.AddField(
            model_name="prestigeclasslanguagerequirement",
            name="prestige_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="character_class.prestigecharacterclass",
            ),
        ),
        migrations.AddField(
            model_name="prestigeclassfeatrequirement",
            name="prestige_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="character_class.prestigecharacterclass",
            ),
        ),
        migrations.AddField(
            model_name="prestigecharacterclass",
            name="required_feats",
            field=models.ManyToManyField(
                blank=True,
                through="character_class.PrestigeClassFeatRequirement",
                to="feat.feat",
            ),
        ),
        migrations.AddField(
            model_name="prestigecharacterclass",
            name="required_languages",
            field=models.ManyToManyField(
                blank=True,
                through="character_class.PrestigeClassLanguageRequirement",
                to="common.language",
            ),
        ),
        migrations.AddField(
            model_name="prestigecharacterclass",
            name="required_race",
            field=models.ManyToManyField(
                blank=True,
                through="character_class.PrestigeClassRaceRequirement",
                to="race.race",
            ),
        ),
        migrations.AddField(
            model_name="prestigecharacterclass",
            name="required_skill_ranks",
            field=models.ManyToManyField(
                blank=True,
                through="character_class.PrestigeClassSkillRankRequirement",
                to="skill.skill",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classalignment",
            unique_together={("character_class", "alignment")},
        ),
        migrations.AlterUniqueTogether(
            name="classbonuslanguage",
            unique_together={("character_class", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="classbsbprogression",
            unique_together={("character_class", "bsb_progression")},
        ),
        migrations.AlterUniqueTogether(
            name="classskill",
            unique_together={("character_class", "skill")},
        ),
        migrations.AlterUniqueTogether(
            name="prestigeclassskillrankrequirement",
            unique_together={("prestige_class", "skill")},
        ),
        migrations.AlterUniqueTogether(
            name="prestigeclassracerequirement",
            unique_together={("prestige_class", "race")},
        ),
        migrations.AlterUniqueTogether(
            name="prestigeclasslanguagerequirement",
            unique_together={("prestige_class", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="prestigeclassfeatrequirement",
            unique_together={("prestige_class", "feat")},
        ),
    ]
