# Generated by Django 5.1.7 on 2025-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="armor",
            name="is_masterwork",
            field=models.BooleanField(default=False),
        ),
    ]
