# Generated by Django 5.1.7 on 2025-03-20 17:11

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[common.validators.validate_year],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
