# Generated by Django 5.1.7 on 2025-04-12 13:46

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("abbreviation", models.CharField(max_length=3, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Abilities",
            },
        ),
        migrations.CreateModel(
            name="Alignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("abbreviation", models.CharField(max_length=2, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Die",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sides",
                    models.IntegerField(
                        unique=True,
                        validators=[utils.validators.validate_positive_integer],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dice",
                "ordering": ["sides"],
            },
        ),
        migrations.CreateModel(
            name="DurationUnit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("name_plural", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "duration_in_seconds",
                    models.IntegerField(
                        validators=[utils.validators.validate_positive_integer]
                    ),
                ),
            ],
            options={
                "ordering": ("duration_in_seconds",),
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_year],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TraitClassification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=4000, null=True),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("alphabet", models.CharField(blank=True, max_length=50, null=True)),
                ("is_secret", models.BooleanField(default=False)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("short_description", models.CharField(max_length=100, unique=True)),
                (
                    "long_description",
                    models.TextField(blank=True, max_length=4000, null=True),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "trait_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.traitclassification",
                    ),
                ),
            ],
            options={
                "ordering": ("short_description",),
            },
        ),
    ]
