# Generated by Django 5.1.7 on 2025-03-20 17:11

import common.validators
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("abbreviation", models.CharField(max_length=2, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("abbreviation", models.CharField(max_length=3, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("short_description", models.CharField(max_length=100, unique=True)),
                (
                    "long_description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TraitClassification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttributeModifier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="character.attribute",
                    ),
                ),
            ],
            options={
                "unique_together": {("value", "attribute")},
            },
        ),
        migrations.CreateModel(
            name="CharacterType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("subtype", models.BooleanField(default=False)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "level_adjustment",
                    models.IntegerField(
                        default=0,
                        validators=[
                            functools.partial(
                                common.validators.validate_integer,
                                *(),
                                **{"max_value": 10, "min_value": 0}
                            )
                        ],
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RaceAttributeModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.attributemodifier",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="character.race"
                    ),
                ),
            ],
            options={
                "unique_together": {("race", "attribute_modifier")},
            },
        ),
        migrations.AddField(
            model_name="race",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                through="character.RaceAttributeModifier",
                to="character.attributemodifier",
            ),
        ),
        migrations.CreateModel(
            name="RaceLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_automatic", models.BooleanField()),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.language",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="character.race"
                    ),
                ),
            ],
            options={
                "unique_together": {("race", "language")},
            },
        ),
        migrations.AddField(
            model_name="race",
            name="languages",
            field=models.ManyToManyField(
                blank=True, through="character.RaceLanguage", to="character.language"
            ),
        ),
        migrations.CreateModel(
            name="CharacterTypeTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.charactertype",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.trait",
                    ),
                ),
            ],
            options={
                "unique_together": {("character_type", "trait")},
            },
        ),
        migrations.AddField(
            model_name="charactertype",
            name="traits",
            field=models.ManyToManyField(
                blank=True, through="character.CharacterTypeTrait", to="character.trait"
            ),
        ),
        migrations.AddField(
            model_name="trait",
            name="trait_classification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="character.traitclassification",
            ),
        ),
    ]
