# Generated by Django 5.1.7 on 2025-04-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterAbilityScore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField(default=10)),
                ("bonus", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Ability Scores",
            },
        ),
        migrations.CreateModel(
            name="CharacterCharacterClass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("level", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name_plural": "Character Classes",
                "ordering": ["character_class__name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterFeat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("level_acquired", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name_plural": "Feats",
                "ordering": ["level_acquired"],
            },
        ),
        migrations.CreateModel(
            name="CharacterInventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name_plural": "Inventories",
                "ordering": ["inventory__name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterLanguage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_automatic", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Languages",
                "ordering": ["language__name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ranks", models.IntegerField(default=0)),
                ("misc_bonus", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Skills",
                "ordering": ["skill__name"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("capacity", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Inventories",
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name_plural": "Inventory Items",
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("level", models.IntegerField(default=1)),
                ("experience", models.IntegerField(default=0)),
                ("current_hit_points", models.IntegerField(default=0)),
                ("max_hit_points", models.IntegerField(default=0)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("height", models.CharField(blank=True, max_length=20, null=True)),
                ("skin_color", models.CharField(blank=True, max_length=20, null=True)),
                ("hair_color", models.CharField(blank=True, max_length=20, null=True)),
                ("eye_color", models.CharField(blank=True, max_length=20, null=True)),
                ("weight", models.CharField(blank=True, max_length=20, null=True)),
                ("spell_resistance", models.IntegerField(default=0)),
                ("fortitude_save_bonus", models.IntegerField(default=0)),
                ("reflex_save_bonus", models.IntegerField(default=0)),
                ("will_save_bonus", models.IntegerField(default=0)),
                ("initiative_bonus", models.IntegerField(default=0)),
                ("speed", models.IntegerField(default=30)),
                ("armor_class", models.IntegerField(default=10)),
                (
                    "alignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.alignment",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
    ]
