# Generated by Django 5.1.7 on 2025-03-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0002_size_language_alphabet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="space_ft",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
